name: 🚀 Deploy website on push
on:
  push:
    branches: master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.sultanbrothers.com
        username: laravel@lappy.innovativeskillsbd.com
        password: ${{ secrets.FTP_PASSWORD }}
